version: "3"
services:
  todotests:
    build: ./todo-app/tests
    depends_on:
      - todofront
      - todoback
    environment:
      - FRONT_HOST=todofront 
  todofront:
    ports:
      - 3000
    build: ./todo-app/front-end
    depends_on:
      - todoback
    environment:
      - REACT_APP_API_HOST=todoback
  todoback:
    ports:
      - 3001
    build: ./todo-app/back-end




